// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/public/Article.vue')['default']
    ArticleList: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/public/ArticleList.vue')['default']
    BirthdayDialog: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/activities/BirthdayDialog.vue')['default']
    BirthdayWarped: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/activities/BirthdayWarped.vue')['default']
    ChatMessage: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/chat/ChatMessage.vue')['default']
    ChatPC: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/chat/ChatPC.vue')['default']
    ChatUser: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/chat/ChatUser.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IndexContent: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/check/IndexContent.vue')['default']
    IndexSideBar: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/check/IndexSideBar.vue')['default']
    Links: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/public/Links/Links.vue')['default']
    MembersCarousel: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/public/MembersCarousel/MembersCarousel.vue')['default']
    Notice: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/public/Notice.vue')['default']
    Protocol: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/public/Protocol.vue')['default']
    RankContent: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/rank/RankContent.vue')['default']
    ReturnTop: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/public/ReturnTop/index.vue')['default']
    SearchIndex: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/search/SearchIndex.vue')['default']
    Select: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/rank/Select.vue')['default']
    SerachDetail: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/search/SerachDetail.vue')['default']
    SideBar: typeof import('F:/i/asoulcnki/ASoulCnkiFrontEndV3/src/components/rank/SideBar.vue')['default']
  }
}

export { }
