name: Deploy Frontend
on:
  push:
    branches: [ main, Moesang/ci ]
    paths:
      - '**'

jobs:
  build:
    name: Build && Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install && \
          npm run build
      - name: Push to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist"
          target: "/var/www/html"
